In [1]:
import pandas as pd

In [2]:
csv=r"C:\Users\VANT\ironhack\ejercicios\w5-data-visuals\data\raw_fighter_details.csv"

fighter_stats=pd.read_csv(csv)

In [3]:
fighter_stats

,fighter_name,Height,Weight,Reach,Stance,DOB,SLpM,Str_Acc,SApM,Str_Def,TD_Avg,TD_Acc,TD_Def,Sub_Avg
0,Tom Aaron,NaN,155 lbs.,NaN,NaN,"Jul 13, 1978",0.00,0%,0.00,0%,0.00,0%,0%,0.0
1,Papy Abedi,"5' 11""",185 lbs.,NaN,Southpaw,"Jun 30, 1978",2.80,55%,3.15,48%,3.47,57%,50%,1.3
2,Shamil Abdurakhimov,"6' 3""",235 lbs.,"76""",Orthodox,"Sep 02, 1981",2.45,44%,2.45,58%,1.23,24%,47%,0.2
3,Danny Abbadi,"5' 11""",155 lbs.,NaN,Orthodox,"Jul 03, 1983",3.29,38%,4.41,57%,0.00,0%,77%,0.0
4,Hiroyuki Abe,"5' 6""",145 lbs.,NaN,Orthodox,NaN,1.71,36%,3.11,63%,0.00,0%,33%,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3591,Zhang Tiequan,"5' 8""",155 lbs.,"69""",Orthodox,"Jul 25, 1978",1.23,36%,2.14,51%,1.95,58%,75%,3.4
3592,Alex Zuniga,NaN,145 lbs.,NaN,NaN,NaN,0.00,0%,0.00,0%,0.00,0%,0%,0.0
3593,George Zuniga,"5' 9""",185 lbs.,NaN,NaN,NaN,7.64,38%,5.45,37%,0.00,0%,100%,0.0
3594,Allan Zuniga,"5' 7""",155 lbs.,"70""",Orthodox,"Apr 04, 1992",3.93,52%,1.80,61%,0.00,0%,57%,1.0
3595,Virgil Zwicker,"6' 2""",205 lbs.,"74""",NaN,"Jun 26, 1982",3.34,48%,4.87,39%,1.31,30%,50%,0.0

In [5]:
volk= fighter_stats[fighter_stats['fighter_name']== 'Alexander Volkanovski']

volk

,fighter_name,Height,Weight,Reach,Stance,DOB,SLpM,Str_Acc,SApM,Str_Def,TD_Avg,TD_Acc,TD_Def,Sub_Avg
3394,Alexander Volkanovski,"5' 6""",145 lbs.,"71""",Orthodox,"Sep 29, 1988",6.02,55%,3.31,60%,2.09,34%,72%,0.3

In [8]:
max_= fighter_stats[fighter_stats['fighter_name']== 'Max Holloway']


max_

,fighter_name,Height,Weight,Reach,Stance,DOB,SLpM,Str_Acc,SApM,Str_Def,TD_Avg,TD_Acc,TD_Def,Sub_Avg
1376,Max Holloway,"5' 11""",145 lbs.,"69""",Orthodox,"Dec 04, 1991",7.26,46%,4.58,60%,0.21,71%,84%,0.3

In [11]:
fighter_stats= pd.concat([volk, max_ ], axis=0)
fighter_stats

,fighter_name,Height,Weight,Reach,Stance,DOB,SLpM,Str_Acc,SApM,Str_Def,TD_Avg,TD_Acc,TD_Def,Sub_Avg
3394,Alexander Volkanovski,"5' 6""",145 lbs.,"71""",Orthodox,"Sep 29, 1988",6.02,55%,3.31,60%,2.09,34%,72%,0.3
1376,Max Holloway,"5' 11""",145 lbs.,"69""",Orthodox,"Dec 04, 1991",7.26,46%,4.58,60%,0.21,71%,84%,0.3