In [1]:
import pandas as pd

In [2]:
csv=r"C:\Users\VANT\ironhack\ejercicios\w5-data-visuals\data\raw_fighter_details.csv"

fighter_stats=pd.read_csv(csv)

In [3]:
fighter_stats

,fighter_name,Height,Weight,Reach,Stance,DOB,SLpM,Str_Acc,SApM,Str_Def,TD_Avg,TD_Acc,TD_Def,Sub_Avg
0,Tom Aaron,NaN,155 lbs.,NaN,NaN,"Jul 13, 1978",0.00,0%,0.00,0%,0.00,0%,0%,0.0
1,Papy Abedi,"5' 11""",185 lbs.,NaN,Southpaw,"Jun 30, 1978",2.80,55%,3.15,48%,3.47,57%,50%,1.3
2,Shamil Abdurakhimov,"6' 3""",235 lbs.,"76""",Orthodox,"Sep 02, 1981",2.45,44%,2.45,58%,1.23,24%,47%,0.2
3,Danny Abbadi,"5' 11""",155 lbs.,NaN,Orthodox,"Jul 03, 1983",3.29,38%,4.41,57%,0.00,0%,77%,0.0
4,Hiroyuki Abe,"5' 6""",145 lbs.,NaN,Orthodox,NaN,1.71,36%,3.11,63%,0.00,0%,33%,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3591,Zhang Tiequan,"5' 8""",155 lbs.,"69""",Orthodox,"Jul 25, 1978",1.23,36%,2.14,51%,1.95,58%,75%,3.4
3592,Alex Zuniga,NaN,145 lbs.,NaN,NaN,NaN,0.00,0%,0.00,0%,0.00,0%,0%,0.0
3593,George Zuniga,"5' 9""",185 lbs.,NaN,NaN,NaN,7.64,38%,5.45,37%,0.00,0%,100%,0.0
3594,Allan Zuniga,"5' 7""",155 lbs.,"70""",Orthodox,"Apr 04, 1992",3.93,52%,1.80,61%,0.00,0%,57%,1.0
3595,Virgil Zwicker,"6' 2""",205 lbs.,"74""",NaN,"Jun 26, 1982",3.34,48%,4.87,39%,1.31,30%,50%,0.0

In [5]:
volk= fighter_stats[fighter_stats['fighter_name']== 'Alexander Volkanovski']

volk

,fighter_name,Height,Weight,Reach,Stance,DOB,SLpM,Str_Acc,SApM,Str_Def,TD_Avg,TD_Acc,TD_Def,Sub_Avg
3394,Alexander Volkanovski,"5' 6""",145 lbs.,"71""",Orthodox,"Sep 29, 1988",6.02,55%,3.31,60%,2.09,34%,72%,0.3

In [8]:
max_= fighter_stats[fighter_stats['fighter_name']== 'Max Holloway']


max_

,fighter_name,Height,Weight,Reach,Stance,DOB,SLpM,Str_Acc,SApM,Str_Def,TD_Avg,TD_Acc,TD_Def,Sub_Avg
1376,Max Holloway,"5' 11""",145 lbs.,"69""",Orthodox,"Dec 04, 1991",7.26,46%,4.58,60%,0.21,71%,84%,0.3

In [65]:
fighter_stats= pd.concat([volk, max_ ], axis=0)
fighter_stats.T

                               3394          1376
fighter_name  Alexander Volkanovski  Max Holloway
Height                        5' 6"        5' 11"
Weight                     145 lbs.      145 lbs.
Reach                           71"           69"
Stance                     Orthodox      Orthodox
DOB                    Sep 29, 1988  Dec 04, 1991
SLpM                           6.02          7.26
Str_Acc                         55%           46%
SApM                           3.31          4.58
Str_Def                         60%           60%
TD_Avg                         2.09          0.21
TD_Acc                          34%           71%
TD_Def                          72%           84%
Sub_Avg                         0.3           0.3

In [13]:
###################################################################################################################################

In [29]:
csv2=r"C:\Users\VANT\ironhack\ejercicios\w5-data-visuals\data\ufc_event_data.csv"

fight_stats=pd.read_csv(csv2)

In [30]:
fight_stats

,Event Name,Event Date,Result,Fighter1,Fighter2,KD,Strikes,TD,Sub,Weight Class,Method,Round,Time
0,UFC Fight Night: Vera vs. Sandhagen,"March 25, 2023",Cory Sandhagen,Cory Sandhagen,Marlon Vera,0-0,128-58,3-0,0-1,Bantamweight,S-DEC,5,5:00
1,UFC Fight Night: Vera vs. Sandhagen,"March 25, 2023",Holly Holm,Holly Holm,Yana Santos,0-0,32-21,4-0,0-0,Women's Bantamweight,U-DEC,3,5:00
2,UFC Fight Night: Vera vs. Sandhagen,"March 25, 2023",Nate Landwehr,Nate Landwehr,Austin Lingo,0-0,64-48,1-0,1-0,Featherweight,SUB-Rear-Naked-Choke,2,4:11
3,UFC Fight Night: Vera vs. Sandhagen,"March 25, 2023",Maycee Barber,Maycee Barber,Andrea Lee,0-0,48-39,2-5,0-0,Women's Flyweight,S-DEC,3,5:00
4,UFC Fight Night: Vera vs. Sandhagen,"March 25, 2023",Albert Duraev,Albert Duraev,Chidi Njokuani,0-0,45-40,2-0,0-0,Middleweight,S-DEC,3,5:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7055,UFC 2: No Way Out,"March 11, 1994",Orlando Wiet,Orlando Wiet,Robert Lucarelli,0-0,8-2,0-1,0-1,Open Weight,KO/TKO,1,2:50
7056,UFC 2: No Way Out,"March 11, 1994",Frank Hamaker,Frank Hamaker,Thaddeus Luster,0-0,2-0,1-0,3-0,Open Weight,SUB-Keylock,1,4:52
7057,UFC 2: No Way Out,"March 11, 1994",Johnny Rhodes,Johnny Rhodes,David Levicki,0-0,11-4,1-0,0-0,Open Weight,KO/TKO-Punches,1,12:13
7058,UFC 2: No Way Out,"March 11, 1994",Patrick Smith,Patrick Smith,Ray Wizard,0-0,1-1,0-0,1-0,Open Weight,SUB-Guillotine-Choke,1,0:58
7059,UFC 2: No Way Out,"March 11, 1994",Scott Morris,Scott Morris,Sean Daugherty,0-0,1-0,1-0,1-0,Open Weight,SUB-Guillotine-Choke,1,0:20

In [37]:
Trilogy= fight_stats[(fight_stats['Fighter2'] == 'Max Holloway')][0:3]
Trilogy

,Event Name,Event Date,Result,Fighter1,Fighter2,KD,Strikes,TD,Sub,Weight Class,Method,Round,Time
367,UFC 276: Adesanya vs. Cannonier,"July 02, 2022",Alexander Volkanovski,Alexander Volkanovski,Max Holloway,0-0,199-127,0-0,0-0,Featherweight,U-DEC,5,5:00
1405,UFC 251: Usman vs. Masvidal,"July 11, 2020",Alexander Volkanovski,Alexander Volkanovski,Max Holloway,0-0,137-102,3-0,0-0,Featherweight,S-DEC,5,5:00
1613,UFC 245: Usman vs. Covington,"December 14, 2019",Alexander Volkanovski,Alexander Volkanovski,Max Holloway,0-0,157-134,0-0,0-0,Featherweight,U-DEC,5,5:00

In [42]:
Trilogy['Event Name'] = Trilogy['Event Name'].str.split(':').str[0]

In [64]:
Trilogy.T

,367,1405,1613
Event Name,UFC 276,UFC 251,UFC 245
Event Date,"July 02, 2022","July 11, 2020","December 14, 2019"
Result,Alexander Volkanovski,Alexander Volkanovski,Alexander Volkanovski
Fighter1,Alexander Volkanovski,Alexander Volkanovski,Alexander Volkanovski
Fighter2,Max Holloway,Max Holloway,Max Holloway
KD,0-0,0-0,0-0
Strikes,199-127,137-102,157-134
TD,0-0,3-0,0-0
Sub,0-0,0-0,0-0
Weight Class,Featherweight,Featherweight,Featherweight
Method,U-DEC,S-DEC,U-DEC
Round,5,5,5
Time,5:00,5:00,5:00

In [57]:
csv3=r"C:\Users\VANT\iron\proyectos\web_scrapin_w4_1\src\api_limpio5.csv"
pd.reset_option('display.max_columns', None)
fighters=pd.read_csv(csv3)

In [58]:
fighters

,Name,Nickname,Division_Title,_Strikes_Landed,_Strikes_Attempted,Takedowns_Landed,Takedowns_Attempted,Striking_accuracy,Takedown_Accuracy,Fighter_Facts,...,Sig_Str_Absorbed,Takedown_avg,Submission_avg,Sig_Str_Defense,Takedown_Defense,Knockdown_Avg,Average_fight_time,First_Round_Finishes,Date,Fighter_id
0,Max Holloway,Blessed,Featherweight Division,3122,6586,4,15,47%,53%,"['Pro since 2010', 'Ten wins by KO, two by sub...",...,4.79,0.28,0.31,60%,84%,0.28,16:08,NaN,NaN,1
1,Alexander Volkanovski,The Great,Featherweight Division,1442,2549,16,67,57%,34%,NaN,...,3.40,1.52,0.20,59%,69%,0.40,17:28,7.0,"Feb. 11, 2023",2

In [80]:
column_to_delete = 'Fighter_Facts'
fighters.drop(column_to_delete, axis=1, inplace=True)

In [81]:
fighters.T

                                              0                        1
Name                               Max Holloway    Alexander Volkanovski
Nickname                                Blessed                The Great
Division_Title           Featherweight Division   Featherweight Division
_Strikes_Landed                            3122                     1442
_Strikes_Attempted                         6586                     2549
Takedowns_Landed                              4                       16
Takedowns_Attempted                          15                       67
Striking_accuracy                           47%                      57%
Takedown_Accuracy                           53%                      34%
Wins                                         24                       25
Losses                                        7                        2
Draws                                         0                        0
Status                                   Active                   Active
Hometown                 Waianae, United States  Shellharbour, Australia
Trains_at             Hawaii Elite MMA - Hawaii   Freestyle Fighting Gym
Fighting_style                        Muay Thai                        0
Age                                          31                       34
Height                                     71.0                     66.0
Weight                                    161.0                    154.5
Octagon_Debut                     Feb. 04, 2012            Oct. 15, 2016
Reach                                      69.0                     71.5
Leg_reach                                  42.0                     36.0
Standing                             2709 (87%)               1085 (75%)
Clinch                                 244 (8%)                 136 (9%)
Ground                                 169 (5%)                221 (15%)
KOTKO                                  10 (43%)                 12 (50%)
DECO                                   11 (48%)                  9 (38%)
SUB                                      2 (9%)                  3 (13%)
Wins_by_Knockout                             10                       12
Wins_by_Submission                            2                        3
Sig_Str_Landed                             7.16                     6.35
Sig_Str_Absorbed                           4.79                      3.4
Takedown_avg                               0.28                     1.52
Submission_avg                             0.31                      0.2
Sig_Str_Defense                             60%                      59%
Takedown_Defense                            84%                      69%
Knockdown_Avg                              0.28                      0.4
Average_fight_time                        16:08                    17:28
First_Round_Finishes                        0.0                      7.0
Date                                          0            Feb. 11, 2023
Fighter_id                                    1                        2

In [82]:
fighters.fillna(0, inplace=True)

In [83]:
fighters

,Name,Nickname,Division_Title,_Strikes_Landed,_Strikes_Attempted,Takedowns_Landed,Takedowns_Attempted,Striking_accuracy,Takedown_Accuracy,Wins,...,Sig_Str_Absorbed,Takedown_avg,Submission_avg,Sig_Str_Defense,Takedown_Defense,Knockdown_Avg,Average_fight_time,First_Round_Finishes,Date,Fighter_id
0,Max Holloway,Blessed,Featherweight Division,3122,6586,4,15,47%,53%,24,...,4.79,0.28,0.31,60%,84%,0.28,16:08,0.0,0,1
1,Alexander Volkanovski,The Great,Featherweight Division,1442,2549,16,67,57%,34%,25,...,3.40,1.52,0.20,59%,69%,0.40,17:28,7.0,"Feb. 11, 2023",2

In [89]:
nueva_columna = ['Alex Volkanovski','Max Holloway']  # Valores para la nueva columna
fighter_stats['name'] = nueva_columna

In [93]:
nueva_columna = ['https://dmxg5wxfqgb4u.cloudfront.net/styles/athlete_bio_full_body/s3/2023-07/VOLKANOVSKI_ALEXANDER_L_BELT_07-08.png?itok=FewlqaNo','https://dmxg5wxfqgb4u.cloudfront.net/styles/athlete_bio_full_body/s3/2023-04/HOLLOWAY_MAX_L_04-15.png?itok=TQ_xcSO-']  # Valores para la nueva columna
fighter_stats['url'] = nueva_columna

In [94]:
fighter_stats

,fighter_name,Height,Weight,Reach,Stance,DOB,SLpM,Str_Acc,SApM,Str_Def,TD_Avg,TD_Acc,TD_Def,Sub_Avg,name,url
3394,Alexander Volkanovski,"5' 6""",145 lbs.,"71""",Orthodox,"Sep 29, 1988",6.02,55%,3.31,60%,2.09,34%,72%,0.3,Alex Volkanovski,https://dmxg5wxfqgb4u.cloudfront.net/styles/at...
1376,Max Holloway,"5' 11""",145 lbs.,"69""",Orthodox,"Dec 04, 1991",7.26,46%,4.58,60%,0.21,71%,84%,0.3,Max Holloway,https://dmxg5wxfqgb4u.cloudfront.net/styles/at...

In [77]:
Trilogy

,Event Name,Event Date,Result,Fighter1,Fighter2,KD,Strikes,TD,Sub,Weight Class,Method,Round,Time
367,UFC 276,"July 02, 2022",Alexander Volkanovski,Alexander Volkanovski,Max Holloway,0-0,199-127,0-0,0-0,Featherweight,U-DEC,5,5:00
1405,UFC 251,"July 11, 2020",Alexander Volkanovski,Alexander Volkanovski,Max Holloway,0-0,137-102,3-0,0-0,Featherweight,S-DEC,5,5:00
1613,UFC 245,"December 14, 2019",Alexander Volkanovski,Alexander Volkanovski,Max Holloway,0-0,157-134,0-0,0-0,Featherweight,U-DEC,5,5:00

In [85]:
output_file_path = 'fighters.csv'
fighters.to_csv(output_file_path, index=False)

In [95]:
output_file_path = 'fighters_stats3.csv'
fighter_stats.to_csv(output_file_path, index=False)

In [87]:
output_file_path = 'Trilogy.csv'
Trilogy.to_csv(output_file_path, index=False)